inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-rails
  - rubocop-rspec

RSpec/DescribeClass:
  Exclude:
  # This cop is n/a for rake tasks
    - spec/lib/tasks/*
  # Allow more descriptive string labels for request specs
    - spec/requests/**/*

# These cops are n/a for rake tasks
RSpec/ContextWording:
  Exclude:
    - spec/support/shared_examples/rake.rb
RSpec/NamedSubject:
  Exclude:
    - spec/lib/tasks/*

# The effort to update the existing specs to align with these cops is too high.
# Future changes to the specs should avoid adding more of these offenses
# and, where possible, remove existing offenses.
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
