inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

RSpec/DescribeClass:
  Exclude:
  # This cop is n/a for rake tasks
    - spec/lib/tasks/*
  # Allow more descriptive string labels for request specs
    - spec/requests/**/*

# Prefer to keep numbers in some let statements
RSpec/IndexedLet:
  Enabled: false

# These cops are n/a for rake tasks
RSpec/ContextWording:
  Exclude:
    - spec/support/shared_examples/rake.rb
RSpec/NamedSubject:
  Exclude:
    - spec/lib/tasks/*
