inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml

plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara

Metrics/AbcSize:
  Exclude:
  # Number of assigments is high but the method is simple and clear
    - app/models/reports/finance_data_report/data_serializer.rb

Metrics/BlockLength:
  Exclude:
    # Not worthwhile refacting now as the offense is marginal and search may be refactored in the near future.
    - app/models/concerns/can_be_searched_like_registration.rb

Metrics/ClassLength:
  Exclude:
  # Not worthwhile refacting now as the offense is marginal and we anticipate refactoring 
  # this serializer anyway once we have more charge and payment data in the system.
    - app/models/reports/finance_data_report/data_serializer.rb

  # keeping it as a single class, as that makes it much easier to maintain, modify, and extend.
    - app/services/audit_trail_diff_service.rb

Metrics/ModuleLength:
  Exclude:
    # these files are simple and easy to read, splitting them into smaller modules would increase complexity for no benefit
    - app/helpers/action_links_helper.rb
    # These specs involve a lot of data so need to be lengthy
    - spec/presenters/reports/exemption_bulk_report_presenter_spec.rb

# Bad cop: Not every method which returns a boolean is a predicate. Some are directives.
Naming/PredicateMethod:
 Enabled: false

RSpec/DescribeClass:
  Exclude:
  # This cop is n/a for rake tasks
    - spec/lib/tasks/**/*
  # Allow more descriptive string labels for request specs
    - spec/requests/**/*

# These cops are n/a for rake tasks
RSpec/ContextWording:
  # Allow a few more prefixes beyond the standard when, with and without
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
  Exclude:
    - spec/support/shared_examples/rake.rb

# Simply changing these variables to "let" results in many cases in an error because "let"
# variables are not available on an example group, only in the scope of an example.
# TODO: Enable this cop and refactor the relevant 137 instances.
RSpec/LeakyLocalVariable:
  Enabled: false

RSpec/NamedSubject:
  Exclude:
    - spec/lib/tasks/*

RSpec/SpecFilePathSuffix:
  Exclude:
    # This isn't really a spec, it uses some rspec-related gems
    - 'spec/manual_benchmarks/bulk_seed_registrations.rb'

Naming/PredicatePrefix:
  Exclude:
    # Presenter column names are driven by the registration field names and can't be changed
    - 'app/presenters/reports/finance_data_report/base_registration_row_presenter.rb'

FactoryBot/ExcessiveCreateList:
  Exclude:
    # testing pagination with a large number of records
    - spec/requests/sites_spec.rb
