dist: trusty

addons:
  postgresql: 9.6
  sonarcloud:
    organization: "defra"

env:
  global:
    - CC_TEST_REPORTER_ID=fbf08922113e16170572601cd555e99b51f71f1acfd8f87c382010182334a034
    - AWS_DAILY_EXPORT_ACCESS_KEY_ID=keyid
    - AWS_DAILY_EXPORT_SECRET_ACCESS_KEY=secretkey
    - AWS_DAILY_EXPORT_BUCKET=daily-exports
    - AWS_BULK_EXPORT_ACCESS_KEY_ID=keyid
    - AWS_BULK_EXPORT_SECRET_ACCESS_KEY=secretkey
    - AWS_BULK_EXPORT_BUCKET=bulk-exports
    - AWS_LETTERS_EXPORT_ACCESS_KEY_ID=keyid
    - AWS_LETTERS_EXPORT_SECRET_ACCESS_KEY=secretkey
    - AWS_LETTERS_EXPORT_BUCKET=letters-exports
    - AWS_BOXI_EXPORT_ACCESS_KEY_ID=keyid
    - AWS_BOXI_EXPORT_SECRET_ACCESS_KEY=secretkey
    - AWS_BOXI_EXPORT_BUCKET=boxi-exports

language: ruby
rvm: 2.7.1
cache: bundler

# Travis CI uses shallow clone to speed up build times, but a truncated SCM
# history may cause issues when SonarCloud computes blame data. To avoid this,
# you can access the full SCM history with `depth: false`
git:
  depth: false

before_install:
  - export TZ=Europe/London
  - gem install bundler --no-ducument
  - sudo apt-get install xvfb -y
  - sudo apt-get install ttf-liberation -y
  - sudo apt-get install wkhtmltopdf -y

before_script:
  # Replace database.yml with database.travis.yml (but leave filename as
  # database.yml). database.travis.yml is the config needed for Travis, and it
  # needs to be in place before we run the migrations.
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec bin/rails db:create --trace
  - RAILS_ENV=test bundle exec bin/rails db:migrate --trace

script:
  - bundle exec rubocop --format progress --format json --out rubocop-result.json
  - bundle exec rspec
  - sonar-scanner
